# Generated by Django 3.1.2 on 2021-03-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='participants',
        ),
    ]
