# Generated by Django 3.1.2 on 2021-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_podcast_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(),
        ),
    ]
