# Generated by Django 3.1.2 on 2021-03-14 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210314_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
