# Generated by Django 3.1.2 on 2021-03-14 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210314_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
