# Generated by Django 3.1.2 on 2021-03-14 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210314_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
